# Generated by Django 5.1.1 on 2024-09-28 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_authore'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='authore',
            new_name='author',
        ),
    ]
